apiVersion: v1
kind: Namespace
metadata:
  name: tic-tac-toe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-game-deploy
  namespace: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttt
  template:
    metadata:
      labels:
        app: ttt
    spec:
      containers:
        - name: ttt-app
          image: ghcr.io/gesatessa/devsecops-cicd_react_ts:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ttt-game-svc
  namespace: tic-tac-toe
spec:
  type: NodePort
  selector:
    app: ttt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
